db:
  user: pguser
  name: jhe-test-ow
  password: test-password
  host: ow-postgres

env:
  SITE_URL: http://localhost:8081
  ALLOWED_HOSTS: 127.0.0.1,localhost

service:
  type: ClusterIP

ingress:
  enabled: true

openWearables:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true

postgres:
  enabled: true
  serviceName: ow-postgres

seed:
  enabled: true
  hook: post-upgrade
  args:
    - --flush-db
    - --with-rich
