db:
  user: pguser
  name: jhe-test-ow
  password: test-password
  # match postgres.serviceName
  host: ow-postgres

env:
  SITE_URL: http://jhe.local.jovyan.org:8081

service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - jhe.local.jovyan.org

openWearables:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - ow.local.jovyan.org

postgres:
  enabled: true
  serviceName: ow-postgres

seed:
  enabled: true
  hook: post-upgrade
  args:
    - --flush-db
    - --with-rich
