{{- if .Values.openWearables.enabled }}
{{- $self := .Values.openWearables.redis }}
{{- $name := "ow-redis" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jhe.fullname" . }}-{{ $name }}
  labels:
    app.kubernetes.io/component: {{ $name }}
    {{- include "jhe.labels" . | nindent 4 }}
spec:
  replicas: {{ $self.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $name }}
      {{- include "jhe.matchLabels" . | nindent 6 }}
  {{- with $self.deploymentStrategy }}
  strategy:
    {{- . | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ $name }}
        {{- include "jhe.matchLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.annotations }}
        {{- .Values.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
    spec:
      nodeSelector: {{ toJson .Values.nodeSelector }}
      containers:
        - name: backend
          image: {{ $self.image }}
          {{- with $self.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $self.resources }}
          resources:
            {{- . | toYaml | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          # envFrom:
          #   - secretRef:
          #       name: {{ include "jhe.fullname" $ }}-ow-redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          {{- if $self.livenessProbe.enabled }}
          livenessProbe:
            {{- include "jhe.probe" $self.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $self.readinessProbe.enabled }}
          readinessProbe:
            {{- include "jhe.probe" $self.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if $self.startupProbe.enabled }}
          startupProbe:
            {{- include "jhe.probe" $self.startupProbe | nindent 12 }}
          {{- end }}
{{- end }}
