{{- if .Values.openWearables.enabled }}
{{- $self := .Values.openWearables.backend }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "jhe.fullname" . }}-ow-backend
  labels:
    {{- include "jhe.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.db }}
  DB_{{ $key | upper }}: {{ $value | print | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.openWearables.backend.env }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
  # some default values (e.g. SECRET_KEY)
  # that should be set once
  {{- $k8s_state := lookup "v1" "Secret" .Release.Namespace (printf "%s-%s" (include "jhe.fullname" .) "ow-backend") | default (dict "data" (dict)) }}
  {{- range $key := $self._secret_env }}
  {{- if not (hasKey $self.env $key) }}
    {{- $key | quote | nindent 2 }}:
    {{- if hasKey $k8s_state.data $key }}
      {{ index $k8s_state.data $key | quote }}
    {{- else }}
      {{- if eq $key "OIDC_RSA_PRIVATE_KEY" }}
      {{ genPrivateKey "rsa" | b64enc | quote }}
      {{- else }}
      {{ randAlphaNum 32 | b64enc | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{- end }}
