{{- if .Values.openWearables.enabled }}
{{- $service := .Values.openWearables.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jhe.fullname" . }}-ow-frontend
  labels:
    {{- include "jhe.labels" . | nindent 4 }}
  {{- with $service.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: ow-frontend
    {{- include "jhe.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
  type: {{ $service.type }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- if eq $service.type "LoadBalancer" }}
  {{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with $service.externalIPs }}
  externalIPs:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
